language: ruby
rvm:
- 2.1

#cache: bundler

script:
  -  jekyll build
  -  htmlproof ./_site --href-ignore https://linkedin.com/

deploy:
  provider: cloudfoundry
  edge: true
  api: $CF_API
  username: $CF_USER
  password: $CF_PASS
  organization: $CF_ORG
  space: $CF_ENV

#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
